[package]
name = "leafpress-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
leafpress = { path = "../leafpress" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clap = { version = "4", features = ["derive", "env"] }

[profile.release]
lto = true
codegen-units = 1
strip = true

[[bin]]
name = "leafpress"
path = "src/main.rs"
