use serde::Deserialize;
use std::{
    env,
    error::Error,
    fs,
    path::{Path, PathBuf},
};

#[derive(Deserialize)]
struct Base16Theme {
    scheme: String,
    author: String,
    base00: String,
    base01: String,
    base02: String,
    base03: String,
    base04: String,
    base05: String,
    base06: String,
    base07: String,
    base08: String,
    base09: String,
    #[serde(rename = "base0A")]
    base0a: String,
    #[serde(rename = "base0B")]
    base0b: String,
    #[serde(rename = "base0C")]
    base0c: String,
    #[serde(rename = "base0D")]
    base0d: String,
    #[serde(rename = "base0E")]
    base0e: String,
    #[serde(rename = "base0F")]
    base0f: String,
}

#[derive(Debug)]
struct Rgb {
    r: u8,
    g: u8,
    b: u8,
}

fn parse_hex(s: &str) -> Result<Rgb, Box<dyn Error>> {
    let s = s.trim().trim_start_matches('#');

    if s.len() != 6 {
        return Err(format!("invalid hexadecimal colour: {s}").into());
    }

    Ok(Rgb {
        r: u8::from_str_radix(&s[0..2], 16)?,
        g: u8::from_str_radix(&s[2..4], 16)?,
        b: u8::from_str_radix(&s[4..6], 16)?,
    })
}

fn parse_theme(path: &Path) -> Result<Base16Theme, Box<dyn Error>> {
    let file = fs::File::open(path)
        .map_err(|error| format!("failed to open theme '{}': {error}", path.display()))?;

    serde_yaml::from_reader(file)
        .map_err(|error| format!("failed to parse theme '{}': {error}", path.display()).into())
}

fn find_yaml_files(dir: &Path) -> Result<Vec<PathBuf>, Box<dyn Error>> {
    let mut files = Vec::new();

    for entry in fs::read_dir(dir)? {
        let path = entry?.path();

        if path.is_file()
            && path
                .extension()
                .is_some_and(|ext| ext.eq_ignore_ascii_case("yaml"))
        {
            files.push(path);
        } else if path.is_dir() {
            for entry in fs::read_dir(path)? {
                let path = entry?.path();

                if path.is_file()
                    && path
                        .extension()
                        .is_some_and(|ext| ext.eq_ignore_ascii_case("yaml"))
                {
                    files.push(path);
                }
            }
        }
    }

    files.sort();
    Ok(files)
}

fn make_identifier(path: &Path) -> String {
    let stem = path.file_stem().unwrap().to_string_lossy();

    let mut identifier = String::new();

    for c in stem.chars() {
        if c.is_ascii_alphanumeric() {
            identifier.push(c.to_ascii_uppercase());
        } else {
            identifier.push('_');
        }
    }

    if identifier
        .chars()
        .next()
        .is_some_and(|c| c.is_ascii_digit())
    {
        identifier.insert(0, '_');
    }

    identifier
}

fn main() -> Result<(), Box<dyn Error>> {
    let themes_dir = Path::new("../../themes");
    let out_dir = PathBuf::from(env::var("OUT_DIR")?);
    let output = out_dir.join("themes.rs");

    println!("cargo:rerun-if-changed={}", themes_dir.display());

    let mut themes = Vec::new();
    for path in find_yaml_files(themes_dir)? {
        let theme = parse_theme(&path)?;
        themes.push((path, theme));
    }

    let mut generated = String::from("// Generated by build.rs; do not edit.\n\n");

    for (path, theme) in &themes {
        let colours = [
            &theme.base00,
            &theme.base01,
            &theme.base02,
            &theme.base03,
            &theme.base04,
            &theme.base05,
            &theme.base06,
            &theme.base07,
            &theme.base08,
            &theme.base09,
            &theme.base0a,
            &theme.base0b,
            &theme.base0c,
            &theme.base0d,
            &theme.base0e,
            &theme.base0f,
        ];

        let colours: Vec<Rgb> = colours
            .into_iter()
            .map(|colour| parse_hex(colour))
            .collect::<Result<_, _>>()?;

        let identifier = make_identifier(path);

        generated.push_str(&format!(
            "pub const {identifier}: StaticPalette = StaticPalette::new(\n"
        ));

        generated.push_str("    [\n");

        for colour in &colours {
            generated.push_str(&format!(
                "        Rgb {{ r: {}, g: {}, b: {} }},\n",
                colour.r, colour.g, colour.b
            ));
        }

        generated.push_str("    ],\n");

        generated.push_str(&format!("    Some({:?}),\n", theme.scheme));
        generated.push_str(&format!("    Some({:?}),\n", theme.author));
        generated.push_str(");\n\n");
    }

    generated.push_str("pub static THEMES: &[(&str, &StaticPalette)] = &[\n");

    for (path, theme) in &themes {
        let identifier = make_identifier(path);

        generated.push_str(&format!("    ({:?}, &{}),\n", theme.scheme, identifier));
    }

    generated.push_str("];\n");

    fs::write(output, generated)?;

    Ok(())
}
