use serde::Deserialize;
use std::{
    env,
    error::Error,
    fs,
    path::{Path, PathBuf},
};

#[derive(Debug, Deserialize)]
pub struct Scheme {
    pub system: String,
    pub name: String,
    pub author: String,
    pub variant: String,
    pub palette: SchemePalette,
}

#[derive(Debug, Deserialize)]
pub struct SchemePalette {
    pub base00: String,
    pub base01: String,
    pub base02: String,
    pub base03: String,
    pub base04: String,
    pub base05: String,
    pub base06: String,
    pub base07: String,
    pub base08: String,
    pub base09: String,
    #[serde(rename = "base0A")]
    pub base0a: String,
    #[serde(rename = "base0B")]
    pub base0b: String,
    #[serde(rename = "base0C")]
    pub base0c: String,
    #[serde(rename = "base0D")]
    pub base0d: String,
    #[serde(rename = "base0E")]
    pub base0e: String,
    #[serde(rename = "base0F")]
    pub base0f: String,
    // Base24 additions
    // pub base10: Option<String>,
    // pub base11: Option<String>,
    // pub base12: Option<String>,
    // pub base13: Option<String>,
    // pub base14: Option<String>,
    // pub base15: Option<String>,
    // pub base16: Option<String>,
    // pub base17: Option<String>,
}

#[derive(Debug)]
struct Rgb {
    r: u8,
    g: u8,
    b: u8,
}

fn parse_hex(s: &str) -> Result<Rgb, Box<dyn Error>> {
    let s = s.trim().trim_start_matches('#');

    if s.len() != 6 {
        return Err(format!("invalid hexadecimal colour: {s}").into());
    }

    Ok(Rgb {
        r: u8::from_str_radix(&s[0..2], 16)?,
        g: u8::from_str_radix(&s[2..4], 16)?,
        b: u8::from_str_radix(&s[4..6], 16)?,
    })
}

fn parse_theme(path: &Path) -> Result<Scheme, Box<dyn Error>> {
    let file = fs::File::open(path)
        .map_err(|error| format!("failed to open theme '{}': {error}", path.display()))?;

    serde_yaml::from_reader(file)
        .map_err(|error| format!("failed to parse theme '{}': {error}", path.display()).into())
}

fn find_yaml_files(dir: &Path) -> Result<Vec<PathBuf>, Box<dyn Error>> {
    let mut files = Vec::new();

    for entry in fs::read_dir(dir)? {
        let path = entry?.path();

        if path.is_file()
            && path
                .extension()
                .is_some_and(|ext| ext.eq_ignore_ascii_case("yaml"))
        {
            files.push(path);
        } else if path.is_dir() {
            for entry in fs::read_dir(path)? {
                let path = entry?.path();

                if path.is_file()
                    && path
                        .extension()
                        .is_some_and(|ext| ext.eq_ignore_ascii_case("yaml"))
                {
                    files.push(path);
                }
            }
        }
    }

    files.sort();
    Ok(files)
}

fn make_identifier(path: &Path) -> String {
    let stem = path.file_stem().unwrap().to_string_lossy();

    let mut identifier = String::new();

    for c in stem.chars() {
        if c.is_ascii_alphanumeric() {
            identifier.push(c.to_ascii_uppercase());
        } else {
            identifier.push('_');
        }
    }

    if identifier
        .chars()
        .next()
        .is_some_and(|c| c.is_ascii_digit())
    {
        identifier.insert(0, '_');
    }

    identifier
}

fn main() -> Result<(), Box<dyn Error>> {
    let base16_dir = Path::new("../../schemes/base16");
    // let base24_dir = Path::new("../../schemes/base24");
    let out_dir = PathBuf::from(env::var("OUT_DIR")?);
    let output = out_dir.join("themes.rs");

    println!("cargo:rerun-if-changed={}", base16_dir.display());
    // println!("cargo:rerun-if-changed={}", base24_dir.display());

    let mut themes = Vec::new();

    for path in find_yaml_files(base16_dir)? {
        let theme = parse_theme(&path)?;
        themes.push((path, theme));
    }
    // for path in find_yaml_files(base24_dir)? {
    //     let theme = parse_theme(&path)?;
    //     themes.push((path, theme));
    // }
    //
    // for path in find_yaml_files(base16_dir)? {
    //     let theme = parse_theme(&path)?;
    //
    //     if !themes
    //         .iter()
    //         .any(|(_, existing)| existing.name == theme.name)
    //     {
    //         themes.push((path, theme));
    //     }
    // }

    let mut generated = String::from("// Generated by build.rs; do not edit.\n\n");

    for (path, theme) in &themes {
        let colours = [
            &theme.palette.base00,
            &theme.palette.base01,
            &theme.palette.base02,
            &theme.palette.base03,
            &theme.palette.base04,
            &theme.palette.base05,
            &theme.palette.base06,
            &theme.palette.base07,
            &theme.palette.base08,
            &theme.palette.base09,
            &theme.palette.base0a,
            &theme.palette.base0b,
            &theme.palette.base0c,
            &theme.palette.base0d,
            &theme.palette.base0e,
            &theme.palette.base0f,
        ];

        let colours: Vec<Rgb> = colours
            .into_iter()
            .map(|colour| parse_hex(colour))
            .collect::<Result<_, _>>()?;

        let identifier = make_identifier(path);

        generated.push_str(&format!(
            "pub const {identifier}: StaticPalette = StaticPalette::new(\n"
        ));

        generated.push_str("    [\n");

        for colour in &colours {
            generated.push_str(&format!(
                "        Rgb {{ r: {}, g: {}, b: {} }},\n",
                colour.r, colour.g, colour.b
            ));
        }

        generated.push_str("    ],\n");

        generated.push_str(&format!("    Some({:?}),\n", theme.name));
        generated.push_str(&format!("    Some({:?}),\n", theme.author));
        generated.push_str(");\n\n");
    }

    generated.push_str("pub static THEMES: &[(&str, &StaticPalette)] = &[\n");

    for (path, theme) in &themes {
        let identifier = make_identifier(path);

        generated.push_str(&format!("    ({:?}, &{}),\n", theme.name, identifier));
    }

    generated.push_str("];\n");

    fs::write(output, generated)?;

    Ok(())
}
